<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-M5HSU70" failures="0" tests="1" name="org.testing.testScripts.TC1" time="32.553" errors="1" timestamp="5 Dec 2024 01:23:58 GMT">
  <testcase classname="org.testing.testScripts.TC1" name="trending" time="32.553">
    <error message="expected:&lt;https://www.youtube.com/&gt; but was:&lt;https://accounts.google.com/v3/signin/challenge/pwd?TL=AKOx4s3LAJyUY74pI8l3YPgd8r03H22QOC4pShXWF-H5qW-nXu22uAyJMJH_X2LO&amp;checkConnection=youtube%3A172&amp;checkedDomains=youtube&amp;cid=1&amp;continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F&amp;ddm=1&amp;dsh=S-1542458032%3A1733361591668591&amp;ec=65620&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;hl=en&amp;ifkv=AcMMx-dJ7qN3F3JjsILZg_NBIyFoLrmH--yyJYUgMSINxj2w7th14YrWRwvPzBnMJhvozUsLG_a1Yg&amp;pstMsg=1&amp;service=youtube&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<https://www.youtube.com/> but was:<https://accounts.google.com/v3/signin/challenge/pwd?TL=AKOx4s3LAJyUY74pI8l3YPgd8r03H22QOC4pShXWF-H5qW-nXu22uAyJMJH_X2LO&checkConnection=youtube%3A172&checkedDomains=youtube&cid=1&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F&ddm=1&dsh=S-1542458032%3A1733361591668591&ec=65620&flowEntry=ServiceLogin&flowName=GlifWebSignIn&hl=en&ifkv=AcMMx-dJ7qN3F3JjsILZg_NBIyFoLrmH--yyJYUgMSINxj2w7th14YrWRwvPzBnMJhvozUsLG_a1Yg&pstMsg=1&service=youtube>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at org.testing.testScripts.TC1.trending(TC1.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase>
</testsuite>
